import type {Metadata} from "next";
import "@/styles/globals.css";
import {Roboto} from 'next/font/google';


const roboto = Roboto({
    weight: ['100', '300', '400', '500', '700', '900'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--Roboto'
})

export const metadata: Metadata = {
    title: 'Oscar PALISSOT | Portfolio data engineer',
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${roboto.variable}`}>
        {children}
        </body>
        </html>
    );
}
