services:
  database-portfolio-web:
    container_name: database-portfolio-web
    image: mariadb:latest
    ports:
      - 65052:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - shared-network

  cache-portfolio-web:
    container_name: cache-portfolio-web
    image: redis:latest
    networks:
      - shared-network

  reverse-proxy-portfolio-web:
    image: caddy:latest
    container_name: reverse-proxy-portfolio-web
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - shared-network
      - edge-network
      
  directus-portfolio-web:
    container_name: directus-portfolio-web
    image: directus/directus:latest
    volumes:
      - ./backend/directus/uploads:/directus/backend/uploads
      - ./backend/directus/database:/directus/database
      - ./backend/directus/extensions:/directus/extensions
    depends_on:
      - cache-portfolio-web
      - database-portfolio-web
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      PUBLIC_URL: ${PUBLIC_URL}
      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"

      # DB CONFIGURATION
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: database-portfolio-web
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

      REDIS_HOST: cache-portfolio-web
      REDIS_PORT: 6379

      CACHE_STORE: "redis"
      RATE_LIMITER_STORE: "redis"
      SYNCHRONIZATION_STORE: "redis"
      MESSENGER_STORE: "redis"

      # DEFAULT ADMIN USER
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      #WEBSOCKETS
      WEBSOCKETS_ENABLED: "true"
      WEBSOCKETS_REST_ENABLED: "true"
      WEBSOCKETS_REST_AUTH: "handshake"
      WEBSOCKETS_REST_AUTH_TIMEOUT: 15

      #STORAGE
      STORAGE_LOCATIONS: "local"
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "./backend/uploads"
    networks:
      - shared-network
      - outbound-network

  frontend-portfolio-web:
    container_name: frontend-portfolio-web
    depends_on:
      - directus-portfolio-web
      - reverse-proxy-portfolio-web
    build:
      context: frontend
      args:
        - NEXT_PUBLIC_ASSETS_URL=${NEXT_PUBLIC_ASSETS_URL}
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    internal: true
  edge-network:
    external: true
  outbound-network:
    driver: bridge

volumes:
  mariadb_data:
    external: true
  caddy_data:
  caddy_config:
